import { Sale, ShopSettings } from '../types';
import { formatINR, sanitizeWhatsAppPhone } from './formatters';

export function buildDailyReportMessage(params: {
  shopSettings: ShopSettings;
  dateStr: string;
  totalSales: number;
  salesCount: number;
  totalProfit: number;
  cashTotal: number;
  upiTotal: number;
  cardTotal: number;
  topProducts: { name: string; count: number }[];
  lowStockCount: number;
  totalExpenses: number;
}): string {
  const {
    shopSettings,
    dateStr,
    totalSales,
    salesCount,
    totalProfit,
    cashTotal,
    upiTotal,
    cardTotal,
    topProducts,
    lowStockCount,
    totalExpenses,
  } = params;

  const topItemsList = topProducts.length > 0 
    ? topProducts.map((p, idx) => `  ${idx + 1}. ${p.name} (${p.count} units)`).join('\n')
    : '  No sales recorded today';

  const lines = [
    `📊 *DAILY BUSINESS SUMMARY*`,
    `🏪 *${shopSettings.shopName.toUpperCase()}*`,
    `📅 *Date:* ${dateStr}`,
    `━━━━━━━━━━━━━━━━━━━━━`,
    `💰 *Total Sales:* ${formatINR(totalSales)} (${salesCount} Bills)`,
    `📈 *Gross Profit:* ${formatINR(totalProfit)}`,
    `💸 *Today's Expenses:* ${formatINR(totalExpenses)}`,
    `✨ *Net Profit:* ${formatINR(totalProfit - totalExpenses)}`,
    `━━━━━━━━━━━━━━━━━━━━━`,
    `💳 *Collection Breakdown:*`,
    `  • Cash: ${formatINR(cashTotal)}`,
    `  • UPI: ${formatINR(upiTotal)}`,
    `  • Card/Bank: ${formatINR(cardTotal)}`,
    `━━━━━━━━━━━━━━━━━━━━━`,
    `📱 *Top Handsets Sold:*`,
    topItemsList,
    `━━━━━━━━━━━━━━━━━━━━━`,
    `⚠️ *Low Stock Alert:* ${lowStockCount} device(s) below threshold`,
    `━━━━━━━━━━━━━━━━━━━━━`,
    `_Generated by Mobikart POS ERP_`,
  ];

  return lines.join('\n');
}

export function buildCustomerInvoiceMessage(sale: Sale, shop: ShopSettings): string {
  const imeiText = sale.imei && sale.imei.length > 0 
    ? `\n*IMEI / Serial:* ${sale.imei.join(', ')}` 
    : '';

  const lines = [
    `🧾 *TAX INVOICE / CASH MEMO*`,
    `🏪 *${shop.shopName}*`,
    `📍 ${shop.address}`,
    `📞 Phone: ${shop.phone}`,
    shop.gst ? `🏛️ GSTIN: ${shop.gst}` : '',
    `━━━━━━━━━━━━━━━━━━━━━`,
    `👤 *Customer:* ${sale.customerName}`,
    `📱 *Contact:* ${sale.customerPhone || 'N/A'}`,
    `🧾 *Invoice No:* ${sale.invoiceNo}`,
    `📅 *Date:* ${new Date(sale.date).toLocaleDateString('en-IN')}`,
    `━━━━━━━━━━━━━━━━━━━━━`,
    `📦 *Item Purchased:* ${sale.product} (Qty: ${sale.qty})${imeiText}`,
    `🛡️ *Warranty:* ${sale.warranty}`,
    `━━━━━━━━━━━━━━━━━━━━━`,
    `💵 *Price:* ${formatINR(sale.sellingPrice)}`,
    sale.discount > 0 ? `🎁 *Discount:* -${formatINR(sale.discount)}` : '',
    `💳 *Total Paid:* *${formatINR(sale.total)}* via ${sale.paymentMode}`,
    `━━━━━━━━━━━━━━━━━━━━━`,
    `🙏 *Thank you for shopping with us!*`,
    `_For any warranty service, please retain this invoice._`,
  ].filter(Boolean);

  return lines.join('\n');
}

export function openWhatsAppDirect(phone: string, text: string) {
  const cleanPhone = phone ? sanitizeWhatsAppPhone(phone) : '';
  const encodedText = encodeURIComponent(text);
  const url = cleanPhone
    ? `https://wa.me/${cleanPhone}?text=${encodedText}`
    : `https://wa.me/?text=${encodedText}`;
  window.open(url, '_blank');
}
